function song = EntryIntoValhalla(octave, speed, rate)
% Entry into Valhalla from Das Rheingold by Richard Wagner
%   Inputs: octave -- integer value to go up or down an octave. 
%                     0 is default; >0 is higher; <0 is lower
%           speed -- integer speed value (default is 1 s per bar in 4/4)
%                    0 is default; >0 is faster; <0 is slower
%           rate -- sample rate for music playback (usually 8192 or 32768)
%   Output: song -- vector for mono or matrix for stereo


% Define anonymous function that creates note for duration t and frequency
% freq and at the defined rate
note = @(t,freq,oct) sin(linspace(0,2*pi*t*freq*2^oct,round(t*rate)));

% Define notes w.r.t. A0 = 27.5 Hz. Octave lets user change octave.
C0 = 13.75*2^(3/12);
C  = C0*2^octave;       % C
Cs = C*2^(1/12); Db=Cs; % C# or Db
D  = C*2^(2/12);        % D
Ds = C*2^(3/12); Eb=Ds; % D# or Eb
E  = C*2^(4/12);        % E
F  = C*2^(5/12);        % F
Fs = C*2^(6/12); Gb=Fs; % F# or Gb
G  = C*2^(7/12);        % G
Gs = C*2^(8/12); Ab=Gs; % G# or Ab
A  = C*2^(9/12);        % A
As = C*2^(10/12); Bb=As;% A# or Bb
B  = C*2^(11/12);       % B
r  = 0;                 % rest

% Assume time signature of 4/4
barLength = 1/2^speed*4;

w = barLength;     %whole note
h = barLength/2;   %half note
t = barLength/3;   %thirds
q = barLength/4;   %quarter note
tt= barLength/6;   %triplet
e = barLength/8;   %eighth note
et= barLength/12;  %"eighth" triplet
s = barLength/16;  %sixteenth note
ss = barLength/32; %thirty-secondth note
sss = barLength/64; %sixty-fourth note

% Creates two-part harmony
song=[% Melody
    (note(q,Ab,3) + note(q,Db,4) + note(q,F,4) + note(q,Ab,4))/4 ...
    (note(q+e,Ab,3) + note(q+e,Db,4) + note(q+e,F,4))/3 ...
    (note(e,F,3) + note(e,Ab,3) + note(e,Db,4))/3 ...
    (note(s+e,Gb,3) + note(s+e,Bb,3))/2 ...
    (note(s,F,3) + note(s,Ab,3) + note(s,Db,4))/3 ...
    (note(e,F,3) + note(e,Ab,3) + note(e,Db,4))/3 ...
    (note(e,Eb,3) + note(e,Ab,3) + note(e,C,4) + note(e,Eb,4))/4 ...
    (note(q,F,3) + note(q,Ab,3) + note(q,Db,4) + note(q,F,4))/4 ...
    (note(q,Ab,3) + note(q,Db,4) + note(q,F,4) + note(q,Ab,4))/4 ...
    (note(q+e,Ab,3) + note(q+e,Db,4) + note(q+e,F,4))/3 ...
    (note(e,F,3) + note(e,Ab,3) + note(e,Db,4))/3 ...
    (note(s+e,Gb,3) + note(s+e,Bb,3))/2 ...
    (note(s,F,3) + note(s,Ab,3) + note(s,Db,4))/3 ...
    (note(e,F,3) + note(e,Ab,3) + note(e,Db,4))/3 ...
    (note(e,Ab,3) + note(e,C,4) + note(e,Eb,4))/3 ...
    (note(s,Ab,3) + note(s,Ab,4))/2 ...
    (note(s+ss,r,4) + note(s+ss,r,4))/2 ...
    (note(ss,Ab,3) + note(ss,Ab,4))/2 ...
    (note(ss,Ab,3) + note(ss,Ab,4))/2 ...
    (note(ss,Ab,3) + note(ss,Ab,4))/2 ...
    (note(s+e,F,3) + note(s+e,Ab,3) + note(s+e,Db,4))/3 ...
    (note(s,Ab,3) + note(s,C,4) + note(s,Eb,4))/3 ...
    (note(e,Ab,3) + note(e,C,4) + note(e,Eb,4))/3 ...
    (note(e,Ab,3) + note(e,Db,4) + note(e,F,4))/3 ...
    (note(s,Ab,3) + note(s,Ab,4))/2 ...
    (note(s+ss,r,4) + note(s+ss,r,4))/2 ...
    (note(ss,Ab,3) + note(ss,Ab,4))/2 ...
    (note(ss,Ab,3) + note(ss,Ab,4))/2 ...
    (note(ss,Ab,3) + note(ss,Ab,4))/2 ...
    (note(s+e,F,3) + note(s+e,Ab,3) + note(s+e,Db,4))/3 ...
    (note(s,Ab,3) + note(s,C,4) + note(s,Eb,4))/3 ...
    (note(e,Ab,3) + note(e,C,4) + note(e,Eb,4))/3 ...
    (note(e,Ab,3) + note(e,Db,4) + note(e,F,4))/3 ...
    (note(s,Db,4) + note(s,Db,5))/2 ...
    (note(s+ss,r,4) + note(s+ss,r,4))/2 ...
    (note(ss,Db,4) + note(ss,Db,5))/2 ...
    (note(ss,Db,4) + note(ss,Db,5))/2 ...
    (note(ss,Db,4) + note(ss,Db,5))/2 ...
    (note(s+e,Bb,3) + note(s+e,Db,3) + note(s+e,Gb,4))/3 ...
    (note(s,Ab,3) + note(s,Db,4) + note(s,F,4) + note(s,Ab,4))/4 ...
    (note(e,Ab,3) + note(e,Db,4) + note(e,F,4) + note(e,Ab,4))/4 ...
    (note(e,Bb,3) + note(e,Db,4) + note(e,Gb,4) + note(e,Bb,4))/4 ...
    (note(s,Db,4) + note(s,Db,5))/2 ...
    (note(s+ss,r,4) + note(s+ss,r,4))/2 ...
    (note(ss,Db,4) + note(ss,Db,5))/2 ...
    (note(ss,Db,4) + note(ss,Db,5))/2 ...
    (note(ss,Db,4) + note(ss,Db,5))/2 ...
    (note(s+e,Bb,3) + note(s+e,Db,3) + note(s+e,Gb,4))/3 ...
    (note(s,Ab,3) + note(s,Db,4) + note(s,F,4) + note(s,Ab,4))/4 ...
    (note(e,Ab,3) + note(e,Db,4) + note(e,F,4) + note(e,Ab,4))/4 ...
    (note(e,Bb,3) + note(e,Db,4) + note(e,Gb,4) + note(e,Bb,4))/4 ...
    (note(s,Bb,3) + note(s,Bb,4))/2 ...
    (note(s+ss,r,3) + note(s+ss,r,4))/2 ...
    (note(ss,Bb,3) + note(ss,Bb,4))/2 ...
    (note(ss,Bb,3) + note(ss,Bb,4))/2 ...
    (note(ss,Bb,3) + note(ss,Bb,4))/2 ...
    (note(s+e,D,4) + note(s+e,F,4) + note(s+e,Bb,4))/3 ...
    (note(s,C,4) + note(s,F,4) + note(s,A,4) + note(s,C,5))/4 ...
    (note(e,C,4) + note(e,F,4) + note(e,A,4) + note(e,C,5))/4 ...
    (note(e,D,4) + note(e,F,4) + note(e,Bb,4) + note(e,D,5))/4 ...
    (note(s,F,4) + note(s,F,5))/2 ...
    (note(s+ss,r,3) + note(s+ss,r,4))/2 ...
    (note(ss,F,4) + note(ss,F,5))/2 ...
    (note(ss,F,4) + note(ss,F,5))/2 ...
    (note(ss,F,4) + note(ss,F,5))/2 ...
    (note(s+e,D,4) + note(s+e,F,4) + note(s+e,Bb,4))/3 ...
    (note(s,C,4) + note(s,F,4) + note(s,A,4) + note(s,C,5))/4 ...
    (note(e,C,4) + note(e,F,4) + note(e,A,4) + note(e,C,5))/4 ...
    (note(e,D,4) + note(e,F,4) + note(e,Bb,4) + note(e,D,5))/4 ...
    (note(s,F,4) + note(s,F,5))/2 ...
    (note(s+ss,r,3) + note(s+ss,r,4))/2 ...
    (note(ss,F,4) + note(ss,F,5))/2 ...
    (note(ss,F,4) + note(ss,F,5))/2 ...
    (note(ss,F,4) + note(ss,F,5))/2 ...
    (note(q,C,4) + note(q,F,4) + note(q,A,4) + note(q,C,5))/4 ...
    (note(q+e,C,4) + note(q+e,F,4) + note(q+e,A,4))/3 ...
    (note(e,A,3) + note(e,C,4) + note(e,F,4))/3 ...
    (note(s+e,F,3) + note(s+e,Bb,3) + note(s+e,D,4))/3 ...
    (note(s,F,3) + note(s,A,3) + note(s,C,4) + note(s,F,4))/4 ...
    (note(e,F,3) + note(e,A,3) + note(e,C,4) + note(e,F,4))/4 ...
    (note(e,Bb,3) + note(e,E,4) + note(e,G,4))/3 ...
    (note(q,A,3) + note(q,F,4) + note(q,A,4))/3 ...
    (note(q,C,4) + note(q,F,4) + note(q,Ab,4) + note(q,C,5))/4 ...
    (note(e+q,C,4) + note(e+q,F,4) + note(e+q,Ab,4))/3 ...
    (note(e,Ab,3) + note(e,C,4) + note(e,F,4))/3 ...
    (note(s+e,F,3) + note(s+e,Bb,3) + note(s+e,Db,4))/3 ...
    (note(s,Ab,3) + note(s,C,4) + note(s,Eb,4))/3 ...
    (note(e,Ab,3) + note(e,C,4) + note(e,Eb,4))/3 ...
    (note(e,Ab,3) + note(e,Db,4) + note(e,F,4))/3 ...
    (note(q+e,C,4) + note(q+e,Eb,4) + note(q+e,Ab,4))/3 ...
    (note(e,Eb,4) + note(e,Ab,4) + note(e,C,4))/3 ...
    (note(s+e,Db,4) + note(s+e,G,4) + note(s+e,Bb,4))/3 ...
    (note(s,C,4) + note(s,Eb,4) + note(s,Ab,4))/3 ...
    (note(q+e,C,4) + note(q+e,Eb,4) + note(q+e,Ab,4))/3 ...
    (note(e,Eb,4) + note(e,Ab,4) + note(e,C,4))/3 ...
    (note(s+e,Db,4) + note(s+e,G,4) + note(s+e,Bb,4))/3 ...
    (note(s,C,4) + note(s,Eb,4))/2 ...
    (note(q,C,4) + note(q,Eb,4) + note(q,Ab,4))/3 ...
    (note(e,Db,4) + note(e,Eb,4) + note(e,Bb,4))/3 ...
    (note(e,C,4) + note(e,Eb,4) + note(e,Ab,4))/3 ...
    (note(e,Db,4) + note(e,Eb,4) + note(e,Bb,4))/3 ...
    (note(e,C,4) + note(e,Eb,4) + note(e,Ab,4))/3 ...
    (note(e,Db,4) + note(e,Eb,4) + note(e,Bb,4))/3 ...
    (note(e,C,4) + note(e,Eb,4) + note(e,Ab,4))/3 ...
    (note(e,Db,4) + note(e,Eb,4) + note(e,Bb,4))/3 ...
    (note(e,C,4) + note(e,Eb,4) + note(e,Ab,4))/3 ...
    (note(e,Db,4) + note(e,Eb,4) + note(e,Bb,4))/3 ...
    (note(e,C,4) + note(e,Eb,4) + note(e,Ab,4))/3 ...
    (note(s+e,Db,4) + note(s+e,Eb,4) + note(s+e,Bb,4))/3 ...
    (note(s,C,4) + note(s,Eb,4) + note(s,Ab,4) + note(s,C,4))/4 ...
    (note(h,C,4) + note(h,Eb,4) + note(h,Ab,4) + note(h,C,4))/4 ...
        
    % Harmony
    (note(h+e,Db,2) + note(h+e,Db,3))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(e+s,Gb,2) + note(e+s,Db,3))/2 ...
    (note(s,Db,2) + note(s,Db,3))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(e,Ab,1) + note(e,Ab,2))/2 ...
    (note(q,Db,2) + note(q,Db,3))/2 ...
    (note(h+e,Db,2) + note(h+e,Db,3))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(e+s,Gb,2) + note(e+s,Db,3))/2 ...
    (note(s,Db,2) + note(s,Db,3))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(e,Ab,1) + note(e,Ab,2))/2 ...
    (note(q,Db,2) + note(q,Db,3) + note(q,Db,4) + note(q,F,4))/4 ...
    (note(s+e,Db,2) + note(s+e,Db,3))/2 ...
    (note(s,Ab,1) + note(s,Ab,2))/2 ...
    (note(e,Ab,1) + note(e,Ab,2))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(q,Db,2) + note(q,Db,3) + note(q,Db,4) + note(q,F,4))/4 ...
    (note(s+e,Db,2) + note(s+e,Db,3))/2 ...
    (note(s,Ab,1) + note(s,Ab,2))/2 ...
    (note(e,Ab,1) + note(e,Ab,2))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(q,Db,2) + note(q,Db,3) + note(q,Db,4) + note(q,F,4))/4 ...
    (note(s+e,Gb,2) + note(s+e,Gb,3))/2 ...
    (note(s,Db,2) + note(s,Db,3))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...    
    (note(e,Gb,2) + note(e,Gb,3))/2 ...
    (note(q,Gb,2) + note(q,Gb,3) + note(q,Gb,4) + note(q,Bb,4))/4 ...
    (note(s+e,Gb,2) + note(s+e,Gb,3))/2 ...
    (note(s,Db,2) + note(s,Db,3))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...    
    (note(e,Gb,2) + note(e,Gb,3))/2 ...
    (note(q,Gb,2) + note(q,Gb,3)+ note(q,Db,4) + note(q,Gb,4) + note(q,Bb,4))/5 ...
    (note(q,F,2) + note(q,F,3))/2 ...
    (note(e,F,2) + note(e,F,3))/2 ...
    (note(e,Bb,2) + note(e,Bb,3))/2 ...
    (note(q,Bb,2) + note(q,Bb,3))/2 ...
    (note(q,F,2) + note(q,F,3) + note(q,Bb,4) + note(q,D,5))/4 ...
    (note(e,F,2) + note(e,F,3))/2 ...
    (note(e,Bb,2) + note(e,Bb,3))/2 ...
    (note(q,Bb,2) + note(q,Bb,3) + note(q,D,4) + note(q,Bb,4) + note(q,D,5))/5 ...
    (note(q,F,2) + note(q,F,3))/2 ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(e,F,1) ...
    (note(e,F,2) + note(e,F,3))/2 ...
    (note(s+e,Bb,1) + note(s+e,Bb,2))/2 ...
    (note(s,F,1) + note(s,F,2))/2 ...
    (note(e,F,1) + note(e,F,2))/2 ...
    (note(e,C,2) + note(e,C,3))/2 ...
    (note(q,F,2) + note(q,F,3))/2 ...
    (note(q,F,2) + note(q,F,3))/2 ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...    
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...
    note(ss,F,1) ...
    note(ss,F,2) ...   
    (note(s+e,Bb,1) + note(s+e,Bb,2))/2 ...
    (note(s,Ab,1) + note(s,Ab,2))/2 ...
    (note(e,Ab,1) + note(e,Ab,2))/2 ...
    (note(e,Db,2) + note(e,Db,3))/2 ...
    (note(q,Ab,1) + note(q,Ab,2))/2 ...
    note(e,Eb,2) ...
    (note(e,Eb,2) + note(e,C,3) + note(e,Eb,3) + note(e,Ab,3))/4 ...
    (note(s+e,Eb,2) + note(s+e,Eb,3) + note(s+e,G,3) + note(s+e,Bb,3))/4 ...
    (note(s,Eb,2) + note(s,Ab,3))/2 ...
    (note(q,C,3) + note(q,Ab,3))/2 ...
     note(e,Eb,2) ...
    (note(e,Eb,2) + note(e,C,3) + note(e,Eb,3) + note(e,Ab,3))/4 ...
    (note(s+e,Eb,2) + note(s+e,Eb,3) + note(s+e,G,3) + note(s+e,Bb,3))/4 ...
    (note(s,Eb,2) + note(s,Ab,3))/2 ...
    (note(q,C,3) + note(q,Ab,3))/2 ...
    (note(e,Eb,3) + note(e,G,3))/2 ...
    (note(e,Ab,2) + note(e,Ab,3))/2 ...
    (note(e,Eb,3) + note(e,G,3))/2 ...
    (note(e,Ab,2) + note(e,Ab,3))/2 ...
    (note(e,Eb,3) + note(e,G,3))/2 ...
    (note(e,Ab,2) + note(e,Ab,3))/2 ...
    (note(e,Eb,3) + note(e,G,3))/2 ...
    (note(e,Ab,2) + note(e,Ab,3))/2 ...
    (note(e,Eb,3) + note(e,G,3))/2 ...
    (note(e,Ab,2) + note(e,Ab,3))/2 ...
    (note(s+e,Eb,3) + note(s+e,G,3))/2 ...
    (note(s,Ab,2) + note(s,Ab,3))/2 ...
    (note(h,Ab,2) + note(h,Eb,3) + note(h,Ab,3))/3 ...
    ];

% Combine two channels into one. Comment out this line for stereo sound
song = sum(song)/2;
