function song = HoC(octave, speed, rate)
% Francis Urquhart's March -- Jim Parker
%   Inputs: octave -- integer value to go up or down an octave. 
%                     0 is default; >0 is higher; <0 is lower
%           speed -- integer speed value (default is 1 s per bar in 4/4)
%                    0 is default; >0 is faster; <0 is slower
%           rate -- sample rate for music playback (usually 8192)
%   Output: song -- vector for mono or matrix for stereo


% Define anonymous function that creates note for duration t and frequency
% freq and at the defined rate
note = @(t,freq,oct) sin(linspace(0,2*pi*t*freq*2^oct,round(t*rate)));

% Define notes w.r.t. A0 = 27.5 Hz. Octave lets user change octave.
A  = 27.5*2^octave;      % A
As = A*2^(1/12);  Bb=As; % A# or Bb
B  = A*2^(2/12);         % B
C  = A*2^(3/12);         % C
Cs = A*2^(4/12);  Db=Cs; % C# or Db
D  = A*2^(5/12);         % D
Ds = A*2^(6/12);  Eb=Ds; % D# or Eb
E  = A*2^(7/12);         % E
F  = A*2^(8/12);         % F
Fs = A*2^(9/12);  Gb=Fs; % F# or Gb
G  = A*2^(10/12);        % G
Gs = A*2^(11/12); Ab=Gs; % G# or Ab
r  = 0;                  % rest

% Assume time signature of 4/4
barLength = 1/2^speed;

w = barLength;     %whole note
h = barLength/2;   %half note
t = barLength/3;   %thirds
q = barLength/4;   %quarter note
tt= barLength/6;   %triplet
e = barLength/8;   %eighth note
et= barLength/12;  %"eighth" triplet
s = barLength/16;  %sixteenth note


% Creates two-part harmony
song=[% melody
    1/2*note(h,D,4)   ...
    1/2*note(w+q+e,D,4)   ...
    1/2*note(e,D,4)   ...
    1/2*note(q+e,Fs,4)   ...
    1/2*note(e,G,4)   ...
    1/2*note(h+w,A,5)   ...
    1/2*note(h,A,5)   ...
    1/2*note(h+q+e,B,5)   ...
    1/2*note(e,A,5)   ...
    1/2*note(q+e,G,4)   ...
    1/2*note(e,B,5)   ...
    1/2*note(q+e,A,5)   ...
    1/2*note(e,G,4)   ...
    1/2*note(h+w,A,5)   ...
    1/2*note(h,A,5)   ...
    1/2*note(h+q+e,A,5)   ...
    1/2*note(e,E,4)   ...
    1/2*note(h,E,4)   ...
    1/2*note(h,A,5)   ...
    1/2*note(w,Fs,4)   ...
    1/2*note(h,D,4)   ...
    1/2*note(h,Fs,4)   ...
    1/2*note(w,E,4)   ...
    1/2*note(q+e,D,4)   ...
    1/2*note(e,Cs,4)   ...
    1/2*note(q+e,B,4)   ...
    1/2*note(e,Cs,4)   ...
    1/2*note(w,D,4)   ...
    note(h,r,0) ...
    note(h,D,3)   ...
    note(w+q+e,D,3)   ...
    note(e,D,3)   ...
    note(q+e,Fs,3)   ...
    note(e,G,3)   ...
    note(h+w,A,4)   ...
    note(h,A,4)   ...
    note(h+q+e,B,4)   ...
    note(e,A,4)   ...
    note(q+e,G,3)   ...
    note(e,B,4)   ...
    note(q+e,A,4)   ...
    note(e,G,3)   ...
    note(h+w,A,4)   ...
    note(h,A,4)   ...
    note(h+q+e,A,4)   ...
    note(e,E,3)   ...
    note(h,E,3)   ...
    note(h,A,4)   ...
    note(w,Fs,3)   ...
    note(h,D,3)   ...
    note(h,Fs,3)   ...
    note(w,E,3)   ...
    note(q+e,D,3)   ...
    note(e,Cs,3)   ...
    note(q+e,B,3)   ...
    note(e,Cs,3)   ...
    note(w,D,3)   ...
 
    % harmony
    1/2*note(18*w+h+q,r,0)          ...
    1/2*note(e,D,4) ... 
    1/2*note(e,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,Fs,4) ...
    1/2*note(q,A,5) ...
    1/2*note(q,Fs,4) ...
    1/2*note(q+e,D,4) ...
    1/2*note(e,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q+e,D,4) ...
    1/2*note(e,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(e,D,4) ...
    1/2*note(e,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,D,4) ...
    1/2*note(q,Fs,4) ...
    1/2*note(q,A,5) ...
    1/2*note(q,Fs,4) ...
    1/2*note(q+e,A,5) ...
    1/2*note(e,A,5) ...
    1/2*note(q,A,5) ...
    1/2*note(q,A,5) ...
    1/2*note(q+e,A,5) ...
    1/2*note(e,A,5) ...
    1/2*note(q,B,5) ...
    1/2*note(q,Cs,5) ...
    1/2*note(w+h,D,5) ...
    1/2*note(h,D,5) ...
    1/2*note(w,B,5) ...
    1/2*note(q+e, A,5) ...
    1/2*note(e, G,4) ...
    1/2*note(q+e, Fs,4) ...
    1/2*note(e,E,4) ...
    1/2*note(w,D,4) ...
];

% Combine two channels into one. Comment out this line for stereo sound
song = sum(song)/2;
