function song = Office(octave, speed, rate)
% Office theme song 
%   Inputs: octave -- integer value to go up or down an octave. 
%                     0 is default; >0 is higher; <0 is lower
%           speed -- integer speed value (default is 1 s per bar in 4/4)
%                    0 is default; >0 is faster; <0 is slower
%           rate -- sample rate for music playback (usually 8192 or 32768)
%   Output: song -- vector for mono or matrix for stereo

% Define anonymous function that creates note for duration t and frequency
% freq and at the defined rate
note = @(t,freq,oct) sin(linspace(0,2*pi*t*freq*2^oct,round(t*rate)));

% Define notes w.r.t. A0 = 27.5 Hz. Octave lets user change octave.
C0 = 13.75*2^(3/12);
C  = C0*2^octave;       % C
Cs = C*2^(1/12); Db=Cs; % C# or Db
D  = C*2^(2/12);        % D
Ds = C*2^(3/12); Eb=Ds; % D# or Eb
E  = C*2^(4/12);        % E
F  = C*2^(5/12);        % F
Fs = C*2^(6/12); Gb=Fs; % F# or Gb
G  = C*2^(7/12);        % G
Gs = C*2^(8/12); Ab=Gs; % G# or Ab
A  = C*2^(9/12);        % A
As = C*2^(10/12); Bb=As;% A# or Bb
B  = C*2^(11/12);       % B
r  = 0;                 % rest

% Assume time signature of 4/4
barLength = 1/2^speed;

w = barLength;     %whole note
h = barLength/2;   %half note
t = barLength/3;   %thirds
q = barLength/4;   %quarter note
tt= barLength/6;   %triplet
e = barLength/8;   %eighth note
et= barLength/12;  %"eighth" triplet
s = barLength/16;  %sixteenth note



% Creates two-part harmony
% Theme
song =[
    (note(e,B,3)+note(e,D,4))/2 ... %bar 1
    note(e,G,3) ...
    (note(h,B,3)+note(h,D,4))/2 ...
    (note(e,B,3)+note(e,D,4))/2 ...
    note(e,G,3) ...
    (note(e,B,3)+note(e,D,4))/2 ... %bar 2
    note(e,Fs,3) ...
    (note(h,B,3)+note(h,D,4))/2 ...
    (note(e,B,3)+note(e,D,4))/2 ...
    note(e,Fs,3) ...
    (note(e,B,3)+note(e,E,4))/2 ... %bar 3
    note(e,G,3) ...
    (note(h,E,4)+note(h,B,3))/2 ...
    (note(e,E,4)+note(e,B,3))/2 ...
    note(e,G,3) ...
    (note(q,E,4)+note(q,C,4))/2 ... %bar 4
    (note(q,E,4)+note(q,C,4))/2 ...
    (note(e,E,4)+note(e,C,4))/2 ...
    note(e,B,3) ...
    note(e,A,3) ...
    note(e,B,3) ...
    (note(e,D,4)+note(e,3,4))/2 ... %bar 5
    note(e,G,3) ...
    (note(h,B,3)+note(h,D,4))/2 ...
    (note(e,B,3)+note(e,D,4))/2 ...
    note(e,G,3) ...
    (note(e,B,3)+note(e,D,4))/2 ... %bar 6
    note(e,Fs,3) ...
    (note(h,B,3)+note(h,D,4))/2 ...
    (note(e,B,3)+note(e,D,4))/2 ...
    note(e,Fs,3) ...
    (note(e,E,4)+note(e,B,3))/2 ... %bar 7
    note(e,G,3) ...
    (note(h,E,4)+note(h,B,3))/2 ...
    (note(e,E,4)+note(e,B,3))/2 ...
    note(e,G,3) ...
    (note(q,E,4)+note(q,C,4))/2 ... %bar 8
    (note(q,E,4)+note(q,C,4))/2 ...
    (note(e,E,4)+note(e,C,4))/2 ...
    note(e,B,3) ...
    note(e,A,3) ...
    note(e,B,3) ...
    (note(e,D,4)+note(e,B,3))/2 ... %bar 9
    note(e,G,3) ...
    (note(h,B,3)+note(h,D,4))/2 ...
    (note(e,B,3)+note(e,D,4))/2 ...
    note(e,G,3) ...
    (note(e,B,3)+note(e,D,4))/2 ... %bar 10
    note(e,Fs,3) ...
    (note(h,B,3)+note(h,D,4))/2 ...
    (note(e,B,3)+note(e,D,4))/2 ...
    note(e,Fs,3) ...
    (note(e,E,4)+note(e,B,3))/2 ... %bar 11
    note(e,G,3) ...
    (note(h,E,4)+note(h,B,3))/2 ...
    (note(e,E,4)+note(e,B,3))/2 ...
    note(e,G,3) ...
    (note(q,E,4)+note(q,C,4))/2 ... %bar 12
    (note(q,E,4)+note(q,C,4))/2 ...
    (note(e,E,4)+note(e,C,4))/2 ...
    note(e,B,3) ...
    note(e,A,3) ...
    note(e,B,3) ...
    note(h,G,3) ... %bar 13
    note(w,G,4)/2 ...
    note(e,Fs,4) ... %bar 14
    note(e,G,4) ...
    note(e,Fs,4) ...
    note(e,D,4) ...
    note(w,E,4) ... %bar 15
    
    
    
    note(w,G,4)/10 ... %1
    note(w,B,3)/10 ... %2
    note(w,E,4)/10 ... %3
    note(w,C,4)/10 ... %4
    note(q,G,4)/10 ... %5
    note(q,G,4)/10 ...
    note(q,G,4)/10 ...
    note(q,G,4)/10 ...
    note(q,B,3)/10 ... %6
    note(q,B,3)/10 ...
    note(q,B,3)/5 ...
    note(q,B,3)/5 ...
    note(q,E,4)/5 ... %7
    note(q,E,4)/5 ...
    note(q,E,4)/5 ...
    note(q,E,4)/5 ...
    note(q,C,4)/5 ... %8
    note(q,C,4)/5 ...
    note(q,C,4)/5 ...
    note(q,C,4)/5 ...
    (note(q,G,4)+note(q,G,3))/6 ... %9
    (note(q,G,4)+note(q,G,3))/6 ...
    (note(q,G,4)+note(q,G,3))/6 ...
    (note(q,G,4)+note(q,G,3))/6 ...
    (note(q,B,3)+note(q,B,2))/6 ... %10
    (note(q,B,3)+note(q,B,2))/6 ...
    (note(q,B,3)+note(q,B,2))/6 ...
    (note(q,B,3)+note(q,B,2))/6 ...
    (note(q,E,4)+note(q,E,3))/6 ... %11
    (note(q,E,4)+note(q,E,3))/6 ... 
    (note(q,E,4)+note(q,E,3))/6 ... 
    (note(q,E,4)+note(q,E,3))/6 ... 
    (note(q,C,4)+note(q,C,3))/6 ... %12
    (note(q,C,4)+note(q,C,3))/6 ...
    (note(q,C,4)+note(q,C,3))/6 ...
    (note(q,C,4)+note(q,C,3))/6 ...
    note(e,G,3)/10 ... %13
    note(e,D,4)/10 ...
    note(e,G,4)/10 ...
    note(e,D,4)/10 ...
    note(e,G,4)/10 ...
    note(e,D,4)/10 ...
    note(e,G,4)/10 ...
    note(e,D,4)/10 ...
    note(e,B,3)/10 ... %14
    note(e,Fs,4)/10 ...
    note(e,B,3)/10 ...
    note(e,Fs,4)/10 ...
    note(e,B,3)/10 ...
    note(e,Fs,4)/10 ...
    note(e,B,3)/10 ...
    note(e,Fs,4)/10 ...
    note(e,E,3)/10 ... %15
    note(e,B,2)/10 ...
    note(e,E,4)/10 ...
    note(e,B,2)/10 ...
    note(e,E,4)/10 ...
    note(e,B,2)/10 ...
    note(e,E,4)/10 ...
    note(e,B,2)/10 ...
    
    
    
    ];

song = sum(song)/2;


    