function song = Passacaglia(octave, speed, rate)
% Passacaglia -- Handel - Halvorsen
% Sounds much better with stereo (comment out last line)
%   Inputs: octave -- integer value to go up or down an octave. 
%                     0 is default; >0 is higher; <0 is lower
%           speed -- integer speed value (default is 1 s per bar in 4/4)
%                    0 is default; >0 is faster; <0 is slower
%           rate -- sample rate for music playback (usually 32768)
%   Output: song -- vector for mono or matrix for stereo


% Define anonymous function that creates note for duration t and frequency
% freq and at the defined rate
note = @(t,freq,oct) sin(linspace(0,2*pi*t*freq*2^oct,round(t*rate)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%% USES OLD DEFINITION OF OCTAVES --- DO NOT FOLLOW %%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Too much time to change and I'm lazy

% Define notes w.r.t. A0 = 27.5 Hz. Octave lets user change octave.
A  = 27.5*2^octave;      % A
As = A*2^(1/12);  Bb=As; % A# or Bb
B  = A*2^(2/12);         % B
C  = A*2^(3/12);         % C
Cs = A*2^(4/12);  Db=Cs; % C# or Db
D  = A*2^(5/12);         % D
Ds = A*2^(6/12);  Eb=Ds; % D# or Eb
E  = A*2^(7/12);         % E
F  = A*2^(8/12);         % F
Fs = A*2^(9/12);  Gb=Fs; % F# or Gb
G  = A*2^(10/12);        % G
Gs = A*2^(11/12); Ab=Gs; % G# or Ab
r  = 0;                  % rest

% Assume time signature of 4/4
barLength = 1/2^speed*2; % too fast on default

w = barLength;     %whole note
h = barLength/2;   %half note
t = barLength/3;   %thirds
q = barLength/4;   %quarter note
tt= barLength/6;   %triplet
e = barLength/8;   %eighth note
et= barLength/12;  %"eighth" triplet
s = barLength/16;  %sixteenth note
ss = barLength/32; %thirty-second note


% Creates two-part harmony
% Theme
theme =[  % violin
       (note(e+s,D,4)+note(e+s,Bb,4))/2 ...
       (note(s,Eb,4)+note(s,C,4))/2  ...
       (note(e+s,C,4)+note(e+s,A,4))/2 ...
       (note(s,D,4)+note(s,Bb,4))/2  ...
       (note(e+s,Eb,4)+note(e+s,C,4))/2 ...
       (note(s,Eb,4)+note(s,C,4))/2  ...
       (note(e+s,D,4)+note(e+s,Bb,4))/2 ...
       (note(s,Eb,4)+note(s,C,4))/2  ...
       (note(e+s,C,4)+note(e+s,A,4))/2 ...
       (note(s,F,4)+note(s,A,4))/2 ...
       (note(e+s,Eb,4)+note(e+s,G,3))/2 ...
       (note(s,F,4)+note(s,A,4))/2 ...
       (note(e+s,D,4)+note(e+s,Bb,4))/2 ...
       (note(s,D,4)+note(s,Bb,4))/2 ...
       (note(e+s,C,4)+note(e+s,A,4))/2 ...
       (note(s,D,4)+note(s,Bb,4))/2 ...
       (note(e+s,Bb,4)+note(e+s,G,3))/2 ...
       (note(s,Bb,4)+note(s,G,3))/2 ...
       (note(e+s,A,4)+note(e+s,Fs,3))/2 ...
       (note(s,Bb,4)+note(s,G,3))/2 ...
       (note(e+s,C,4)+note(e+s,A,4))/2 ...
       (note(s,C,4)+note(s,A,4))/2 ...
       (note(e+s,Bb,4)+note(e+s,G,3))/2 ...
       (note(s,C,4)+note(s,A,4))/2 ...
       (note(e+s,A,4)+note(e+s,Fs,3))/2 ...
       (note(s,D,4)+note(s,Fs,3))/2 ...
       (note(e+s,C,4)+note(e+s,E,3))/2 ...
       (note(s,D,4)+note(s,Fs,3))/2 ...
       (note(e+s,Bb,4)+note(e+s,G,3))/2 ...
       note(s,A,4) ...
       note(q,G,3) ...
           
       % viola
       note(h,G,3) ...
       note(h,Eb,3) ...
       note(h,F,3) ...
       note(h,Bb,3) ...
       note(h,Eb,3) ...
       note(h,C,3) ...
       note(q,D,3) ...
       note(q,D,2) ...
       note(h,G,2)
];

% Variation 1
var1 = [% violin
        (note(q+e,D,4)+note(q+e,Bb,4))/2 ...
        (note(e,D,4)+note(e,Bb,4))/2 ...
        (note(q+e,Eb,4)+note(q+e,C,4))/2 ...
        (note(e,D,4)+note(e,Bb,4))/2 ...
        (note(q+e,C,4)+note(q+e,A,4))/2 ...
        (note(e,C,4)+note(e,A,4))/2 ...
        (note(q+e,D,4)+note(q+e,Bb,4))/2 ...
        (note(e,C,4)+note(e,A,4))/2 ...
        (note(q+e,Bb,4)+note(q+e,G,3))/2 ...
        (note(e,Bb,4)+note(e,G,3))/2 ...
        (note(q+e,C,4)+note(q+e,A,4))/2 ...
        (note(e,Bb,4)+note(e,G,3))/2 ...
        (note(q,A,4)+note(q,Fs,3))/2 ...
        note(q,D,4) ...
        note(e+s,Bb,4) ...
        note(s,A,4) ...
        note(q,G,3) ...
        
        % viola
        note(s,G,2) ...
        note(s,G,3) ...
        note(e,F,3) ...
        note(e,Eb,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,D,3) ...
        note(e,Eb,3) ...
        note(e,C,3) ...
        note(e,F,3) ...
        note(e,Eb,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,C,3) ...
        note(e,D,3) ...
        note(e,Bb,3) ...
        note(e,Eb,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        note(e,Bb,3) ...
        note(e,C,3) ...
        note(e,A,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        note(e,G,2) ...
        note(e,D,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        ];
 
% Variation 2   
var2 = [%violin
        note(e,Bb,4) ...
        note(e,D,4) ...
        note(e,G,4) ...
        note(e,F,4) ...
        note(e,Eb,4) ...
        note(e,D,4) ...
        note(e,C,4) ...
        note(e,Bb,4) ...
        note(e,A,4) ...
        note(e,C,4) ...
        note(e,F,4) ...
        note(e,Eb,4) ...
        note(e,D,4) ...
        note(e,C,4) ...
        note(e,Bb,4) ...
        note(e,A,4) ...
        note(e,G,3) ...
        note(e,Bb,4) ...
        note(e,Eb,4) ...
        note(e,D,4) ...
        note(e,C,4) ...
        note(e,Bb,4) ...
        note(e,A,4) ...
        note(e,G,3) ...
        note(e,Fs,3) ...
        note(e,A,4) ...
        note(e,D,4) ...
        note(e,C,4) ...
        note(e,Bb,4) ...
        note(e,A,4) ...
        note(q,G,3) ...
        note(ss,G,3) ...
        note(ss,A,4) ...
        note(ss,G,3) ...
        note(ss,A,4) ...
        note(ss,G,3) ...
        note(ss,A,4) ...
        note(ss,Fs,3) ...
        note(ss,G,3) ...
        note(e,Bb,4) ...
        note(e,r,0) ...
        note(e,C,4) ...
        note(e,r,0) ...
        note(ss,Eb,4) ...
        note(e-ss,Eb,5) ...
        note(e,r,0) ...
        note(ss,F,3) ...
        note(ss,G,3) ...
        note(ss,F,3) ...
        note(ss,G,3) ...
        note(ss,F,3) ...
        note(ss,G,3) ...
        note(ss,E,3) ...
        note(ss,F,3) ...
        note(e,A,4) ...
        note(e,r,0) ...
        note(e,Bb,4) ...
        note(e,r,0) ...
        note(ss,D,4) ...
        note(e-ss,D,5) ...
        note(e,r,0) ...
        note(ss,Eb,3) ...
        note(ss,F,3) ...
        note(ss,Eb,3) ...
        note(ss,F,3) ...
        note(ss,Eb,3) ...
        note(ss,F,3) ...
        note(ss,D,3) ...
        note(ss,E,3) ...
        note(e,G,3) ...
        note(e,r,0) ...
        note(e,A,4) ...
        note(e,r,0) ...
        note(ss,C,4) ...
        note(e-ss,C,5) ...
        note(e,r,0) ...
        note(ss,D,4) ...
        note(e-ss,D,5) ...
        note(e,r,0) ...
        note(ss,Fs,4) ...
        note(e-ss,Fs,5) ...
        note(e,r,0) ...
        note(ss,G,4) ...
        note(e-ss+e,G,5) ...
        note(q,r,0);
    
        % viola
        note(q,G,2) ...
        note(q,Bb,3) ...
        note(e,C,3) ...
        note(e,r,0) ...
        note(e,Eb,2) ...
        note(e,r,0) ...
        note(q,F,2) ...
        note(q,A,3) ...
        note(e,Bb,3) ...
        note(e,r,0) ...
        note(e,D,2) ...
        note(e,r,0) ...
        note(q,Eb,2) ...
        note(q,G,2) ...
        note(e,A,3) ...
        note(e,r,0) ...
        note(e,C,2) ...
        note(e,r,0) ...
        note(q,D,2) ...
        note(q,Fs,2) ...
        note(q+e,G,2) ...
        note(e,A,3) ...
        note(e,Bb,3) ...
        note(e,D,3) ...
        note(e,G,3) ...
        note(e,F,3) ...
        note(e,Eb,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        note(e,C,3) ...
        note(e,F,3) ...
        note(e,Eb,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        note(e,G,2) ...
        note(e,Bb,3) ...
        note(e,Eb,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        note(e,G,2) ...
        note(e,Fs,2) ...
        note(e,A,3) ...
        note(e,D,3) ...
        note(e,C,3) ...
        note(e,Bb,3) ...
        note(e,A,3) ...
        note(q,G,2) ...
    ];
    
finale = [
    %violin
    
        (note(s,D,4)+note(s,Bb,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Eb,4)+note(s,C,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        (note(s,Eb,4)+note(s,C,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Eb,4)+note(s,C,4))/2 ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Eb,4)+note(s,C,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,F,4)+note(s,A,4))/2 ...
        (note(s,Eb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,F,4)+note(s,A,4))/2 ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,A,4))/2 ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,A,4))/2 ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Fs,3))/2 ...
        (note(s,C,4)+note(s,E,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Fs,3))/2 ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        (note(s,G,3)+note(s,Bb,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,G,4)+note(s,Bb,4))/2 ...
        (note(s,G,4)+note(s,B,4))/2 ...
        (note(s,G,2)+note(s,D,3))/2 ...
        (note(s,G,2)+note(s,D,3))/2 ...
        (note(s,Gs,4)+note(s,B,4))/2 ...
        (note(s,Fs,4)+note(s,B,4))/2 ...
        (note(s,G,2)+note(s,D,3))/2 ...
        (note(s,G,2)+note(s,D,3))/2 ...
        (note(s,G,4)+note(s,B,4))/2 ...
        (note(s,G,4)+note(s,C,4))/2 ...
        (note(s,G,2)+note(s,Eb,3))/2 ...
        (note(s,G,2)+note(s,Eb,3))/2 ...
        (note(s,Gs,4)+note(s,C,4))/2 ...
        (note(s,Fs,4)+note(s,C,4))/2 ...
        (note(s,G,2)+note(s,Eb,3))/2 ...
        (note(s,G,2)+note(s,Eb,3))/2 ...
        (note(s,G,4)+note(s,C,4))/2 ...
        (note(s,A,5)+note(s,Cs,4))/2 ...
        (note(s,G,2)+note(s,E,3))/2 ...
        (note(s,G,2)+note(s,E,3))/2 ...
        (note(s,Bb,5)+note(s,Cs,4))/2 ...
        (note(s,Gs,4)+note(s,Cs,4))/2 ...
        (note(s,G,2)+note(s,E,3))/2 ...
        (note(s,G,2)+note(s,E,3))/2 ...
        (note(s,A,5)+note(s,Cs,4))/2 ...
        (note(s,Bb,5)+note(s,D,4))/2 ...
        (note(s,G,2)+note(s,F,3))/2 ...
        (note(s,G,2)+note(s,F,3))/2 ...
        (note(s,C,4)+note(s,D,4))/2 ...
        (note(s,A,4)+note(s,D,4))/2 ...
        (note(s,G,2)+note(s,F,3))/2 ...
        (note(s,G,2)+note(s,F,3))/2 ...
        (note(s,Bb,5)+note(s,D,4))/2 ...
        (note(s,B,4)+note(s,D,4))/2 ...
        (note(s,G,2)+note(s,F,3))/2 ...
        (note(s,G,2)+note(s,F,3))/2 ...
        (note(s,B,5)+note(s,D,4))/2 ...
        (note(s,C,5)+note(s,Eb,4))/2 ...
        (note(s,G,2)+note(s,Fs,3))/2 ...
        (note(s,G,2)+note(s,Fs,3))/2 ...
        (note(s,C,5)+note(s,Eb,4))/2 ...
        (note(s,Cs,5)+note(s,E,4))/2 ...
        (note(s,G,2)+note(s,G,3))/2 ...
        (note(s,G,2)+note(s,G,3))/2 ...
        (note(s,Cs,5)+note(s,E,4))/2 ...
        (note(s,E,5)+note(s,G,4))/2 ...
        (note(s,G,2)+note(s,Bb,4))/2 ...
        (note(s,G,2)+note(s,Bb,4))/2 ...
        (note(s,E,5)+note(s,G,4))/2 ...
        (note(s,G,5)+note(s,Bb,5))/2 ...
        (note(s,G,2)+note(s,Cs,4))/2 ...
        (note(s,G,2)+note(s,Cs,4))/2 ...
        (note(s,G,5)+note(s,Bb,5))/2 ...
        (note(s,Bb,6)+note(s,Cs,5))/2 ...
        (note(s,G,2)+note(s,E,4))/2 ...
        (note(s,G,2)+note(s,E,4))/2 ...
        (note(s,Bb,6)+note(s,Cs,5))/2 ...
        (note(q,Cs,6)+note(q,E,5))/2 ...
        note(q,r,0) ... 
        (note(q,D,4)+note(q,G,3))/2 ...
        (note(q,D,4)+note(q,F,3))/2 ...
        (note(h,D,4)+note(h,Eb,3)+note(h,G,3))/3 ...
        (note(q,C,4)+note(q,Eb,3))/2 ...
        (note(q,Bb,4)+note(q,Eb,3))/2 ...
        (note(h,A,4)+note(h,G,3))/2 ...
        (note(q+e,A,4)+note(q+e,Fs,3))/2 ...
        note(e,G,3) ...
        (note(w,G,3)+note(w,B,3))/2 ...

   
        % viola
        note(s,G,2) ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,A,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Eb,4)+note(s,C,4))/2 ...
        (note(s,Eb,4)+note(s,C,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,A,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Eb,4)+note(s,G,3))/2 ...
        (note(s,Eb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        (note(s,D,4)+note(s,Bb,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,A,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,A,4))/2 ...
        (note(s,C,4)+note(s,A,4))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        (note(s,Bb,4)+note(s,G,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,C,4)+note(s,E,3))/2 ...
        (note(s,C,4)+note(s,E,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        (note(s,A,4)+note(s,Fs,3))/2 ...
        note(s,G,2) ...
        note(s,G,2) ...
        (note(s,G,3)+note(s,Bb,3))/2 ...
        (note(s,G,3)+note(s,Bb,3))/2 ...
        note(s,G,2) ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,B,4)+note(s,Fs,3))/2 ...
        (note(s,B,4)+note(s,Fs,3))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,B,4)+note(s,Fs,3))/2 ...
        (note(s,B,4)+note(s,Fs,3))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,Eb,3)+note(s,G,2))/2 ...
        (note(s,C,4)+note(s,Eb,3))/2 ...
        (note(s,C,4)+note(s,Eb,3))/2 ...
        (note(s,Eb,3)+note(s,G,2))/2 ...
        (note(s,Eb,3)+note(s,G,2))/2 ...
        (note(s,C,4)+note(s,Eb,3))/2 ...
        (note(s,C,4)+note(s,Eb,3))/2 ...
        (note(s,Eb,3)+note(s,G,2))/2 ...
        (note(s,E,3)+note(s,G,2))/2 ...
        (note(s,Cs,4)+note(s,E,3))/2 ...
        (note(s,Cs,4)+note(s,E,3))/2 ...
        (note(s,E,3)+note(s,G,2))/2 ...
        (note(s,E,3)+note(s,G,2))/2 ...
        (note(s,Cs,4)+note(s,E,3))/2 ...
        (note(s,Cs,4)+note(s,E,3))/2 ...
        (note(s,E,3)+note(s,G,2))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,D,4)+note(s,F,3))/2 ...
        (note(s,D,4)+note(s,F,3))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,D,4)+note(s,F,3))/2 ...
        (note(s,D,4)+note(s,F,3))/2 ...
        (note(s,F,3)+note(s,G,2))/2 ...
        (note(s,D,3)+note(s,G,2))/2 ...
        (note(s,B,4)+note(s,D,3))/2 ...
        (note(s,B,4)+note(s,D,3))/2 ...
        (note(s,D,3)+note(s,G,2))/2 ...
        (note(s,Eb,3)+note(s,G,2))/2 ...
        (note(s,C,4)+note(s,Eb,3))/2 ...
        (note(s,C,4)+note(s,Eb,3))/2 ...
        (note(s,Eb,3)+note(s,G,2))/2 ...
        (note(s,E,3)+note(s,G,2))/2 ...
        (note(s,Cs,4)+note(s,E,3))/2 ...
        (note(s,Cs,4)+note(s,E,3))/2 ...
        (note(s,E,3)+note(s,G,2))/2 ...
        (note(s,G,3)+note(s,G,2))/2 ...
        (note(s,E,4)+note(s,G,3))/2 ...
        (note(s,E,4)+note(s,G,3))/2 ...
        (note(s,G,3)+note(s,G,2))/2 ...
        (note(s,Bb,4)+note(s,G,2))/2 ...
        (note(s,G,4)+note(s,Bb,4))/2 ...
        (note(s,G,4)+note(s,Bb,4))/2 ...
        (note(s,Bb,4)+note(s,G,2))/2 ...
        (note(s,Cs,4)+note(s,G,2))/2 ...
        (note(s,Bb,5)+note(s,Cs,4))/2 ...
        (note(s,Bb,5)+note(s,Cs,4))/2 ...
        (note(s,Cs,4)+note(s,G,2))/2 ...
        (note(q,Bb,5)+note(q,Cs,4)+note(q,G,2))/3 ...
        note(q,r,0) ... 
        (note(h,D,3)+note(h,Bb,3))/2 ...
        (note(h,D,3)+note(h,C,2))/2 ...
        (note(q,C,3)+note(q,C,2))/2 ...
        (note(q,Bb,3)+note(q,C,2))/2 ...
        (note(q,A,3)+note(q,D,2))/2 ...
        (note(q,D,3)+note(q,D,2))/2 ...
        (note(h,C,3)+note(h,D,2))/2 ...
        (note(w,D,3)+note(w,G,2))/2 ...

    ];
    
song = [theme var1 var2 finale];

% Combine two channels into one. Comment out this line for stereo sound
% Sounds much better with two channels...
song = sum(song)/2;   
